---
title: "Automatisation de la science"
author: "Laurence-Olivier M. Foisy"
format:
  revealjs: 
    theme: beige
    logo: ul_logo.png
    footer: "Automatisation de la science"
---

## Que sont les GML ?

:::: {.columns}

::: {.column width="50%"}
### Modèles propriétaires
- GPT
- Bard
- Claude
:::

::: {.column width="50%"}
### Modèles libres d'accès
- Llama
- Mistral
:::

::::

## Deux questions:
- Quels sont les éléments constitutifs d'une recherche en analyse de sondages au Canada et plus précisément, les éléments d'une revue de littérature en analyse de sondages au Canada?
- Comment les technologies d'intelligence artificielle (IA) peuvent-elles être utilisées pour automatiser les processus scientifique de recherche, d'analyse et de rédaction?

## Cadre opératoire
### Deux étapes

- Méta-analyse des éléments constitutifs de la recherche en analyse de sondages
- Preuve de concept: Automatisation de la rédaction de revue de littérature en recherche en analyse de sondages

## Méta-Analyse {background-color="aquamarine"}

- Étude de cas: Analyse de sondages au Canada
- Revue systématique en 24 étapes

## Preuve de concept

::: {.incremental}
- Peaufinage des modèles
- Développement d'un prototype
- Évaluation du prototype
:::

## Slide with speaker notes

Slide content

::: {.notes}
Speaker notes go here.
:::